/* eslint-disable prettier/prettier */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';
import CreatePostModal from './components/modals/CreatePostModal';
import { Providers } from './providers/Provider';
import { cn } from './lib/utils';
import { ClerkProvider } from '@clerk/nextjs';
const inter = Inter({ subsets: ['latin'] });
const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next - Social Platform',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(nunito.className, 'bg-[#F2F2F2]')}>
          <Providers>
            {children}
          </Providers>
        </body>
      </html >
    </ClerkProvider>
  );
}
